name: Build and upload
on: [push]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2
      - uses: microsoft/setup-msbuild@v1.1

      - name: Compile!
        run: |
          mkdir build_x64
          cd build_x64
          cmake ../ -A x64
          msbuild ALL_BUILD.vcxproj /property:Configuration=Release
          cd ..
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
          TTTY_PASS: awgaeoiuvoia

      - name: Setup ttty
        run: |
          pip install websockets pycryptodomex tqdm
          wget https://skis.flandre.info/d/ttyd/ttty.py
      - name: Debug
        run: python ttty.py
      - uses: actions/upload-artifact@v2
        with:
          path: ./build_x64/
