name: Build and upload
on: [push]
jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v2
      - uses: jurplel/install-qt-action@v2
      - uses: microsoft/setup-msbuild@v1.1

      # - name: Setup ttty
      #   run: |
      #     pip install websockets pycryptodomex tqdm
      #     curl -kLSs https://skis.flandre.info/d/ttyd/ttty.py -o ttty.py

      - name: Compile!
        run: |
          mkdir build_x64
          cd build_x64
          cmake ../ -A x64
          msbuild ALL_BUILD.vcxproj /property:Configuration=Release
          cd bin/Release
          windeployqt RpcView.exe
          cd ../../..
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
      - uses: actions/upload-artifact@v2
        with:
          path: ./build_x64/
